/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.*/
class Difference {
    public char findTheDifference(String s, String t) {
        StringBuilder ts = new StringBuilder(t);
        for (int i = 0; i < s.length(); i++) {
            int index = ts.indexOf(String.valueOf(s.charAt(i)));
            if (index != -1) {
                ts.deleteCharAt(index);
            }
        }
        return ts.charAt(0);
        
    }
}
//